- name: superapp-openstack
  hosts: openstack

  tasks: 
  - name: create a postgres deployment
    script: heat-postgres/deploy.sh {{ flavor }} {{ pgsql_user }} {{ pgsql_pass }} {{ pgsql_db }}
    register: resultopenstack

  - name: debug
    debug: var=resultopenstack.stdout

- name: superapp-openshift
  hosts: openshift

  tasks:
  - name: create an openshift application
    script: deploy-java {{ hostvars[groups['openstack'][0]]['resultopenstack'].stdout }} {{ pgsql_user }} {{ pgsql_pass }} {{ pgsql_db }}
    become: yes
    register: resultopenshift

  - name: debug
    debug: var1=resultopenshift.stdout
