heat_template_version: 2015-04-30

description: Design Practice Workshop (PostgreSQL Example)

parameters:
  key_name:
    type: string
    description:
      Name of an existing key pair to enable SSH access to the instance.
    default: default
  image:
    type: string
    description: ID of the image to use for the instance to be created.
    default: rhel7
  instance_type:
    type: string
    description: Type of the instance to be created.
    default: m1.medium
  public_net:
    type: string
    description: >
      Public network for which floating IP addresses will be allocated
    default: public_network
  private_net:
    type: string
    description: Private network into which servers get deployed
    default: private_network
  private_subnet:
    type: string
    description: Private subnet into which servers get deployed
    default: private_subnet
  pgsql_user:
    type: string
    description: Username to use for the PostgreSQL database
    default: pguser
  pgsql_pass:
    type: string
    description: Password to use for the PostgreSQL database
    default: pgpass
  pgsql_db:
    type: string
    description: Database to use for the PostgreSQL server
    default: pgdatabase

resources:
  postgres_srv:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: instance_type }
      networks:
        - port: { get_resource: postgres_port }
      user_data_format: RAW
      user_data:
        get_resource: postgres_config

  postgres_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: private_net }
      fixed_ips:
        - subnet: { get_param: private_subnet }
      security_groups: [{ get_resource: postgres_secgroup }]

  postgres_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }
      port_id: { get_resource: postgres_port }

  postgres_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Add security group rules for server
      name: security-group
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 5432
          port_range_max: 5432
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp

  postgres_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ungrouped
      config: |
        #!/usr/bin/env bash
        rpm -Uvh http://sat6.e2e.bos.redhat.com/pub/katello-ca-consumer-latest.noarch.rpm
        subscription-manager register --org="e2e" --activationkey="e2e-base-key"
        yum install postgresql postgresql-server -y
        #firewall-cmd --add-port=5432/tcp
        postgresql-setup initdb
        systemctl enable postgresql
        systemctl start postgresql
        #TODO - configure postgresql database

outputs:
  instance_ip:
    description: Public IP address of the newly created Nova instance.
    value: { get_attr: [ postgres_floating_ip, floating_ip_address ] }

